### ISSUE TITLE
Server Construction

### ISSUE THREAD

**Issue by khuynh2002** [SecurityLogMiner/log-collection-server#2]
We will want to create a development server (or multiple) to begin testing the client-server communication. The server will be cloud-hosted on AWS.

_Tasks in progress_

**Comment by endepointe** [comment]
Using Terraform to manage AWS is an opotion:

https://developer.hashicorp.com/terraform/tutorials/aws

**Comment by endepointe** [comment]
closing as duplicate exists here:
https://github.com/SecurityLogMiner/log-collection-server/issues/6
