### ISSUE TITLE
create an admin account that we all have access to

### ISSUE THREAD

**Issue by murchej** [SecurityLogMiner/log-collection-server#5]
See https://github.com/SecurityLogMiner/log-collection-client/issues/26

**Comment by Jicxer** [comment]
Was this resolved with our discussion on the retrospective video?
We could just have access to the github admin account unless you're referring to AWS admin account?

**Comment by slm-admin** [comment]
created this admin account. will distribute email credentials and recovery code

**Comment by slm-admin** [comment]
creds sent.
decrypt the files sent in discord using:

openssl enc -aes128 -pbkdf2 -d -in file.aes128 -out file.txt -pass pass:<password>
